[droidian-release] Downgrade libnotify-bin dependency to a recommendation
It is a nice eye-candy, but we don't strictly depend on it.

Having it as a dependency makes it pull in quite a lot of stuff
in the Droidian Docker base images, which is not something that
we want...

Signed-off-by: Eugenio Paolantonio (g7) <me@medesimo.eu>

diff --git a/runonce/scripts/droidian-upgrade b/runonce/scripts/droidian-upgrade
--- a/runonce/scripts/droidian-upgrade
+++ b/runonce/scripts/droidian-upgrade
@@ -7,6 +7,11 @@ send_notification() {
 	subject="${2}"
 	body="${3}"
 
+	if ! which notify-send &>/dev/null; then
+		echo "E: notify-send not found, unable to send upgrade complete notification" >&2
+		return 1
+	fi
+
 	notify-send \
 		-a "${NAME}" \
 		-i emblem-droidian \
@@ -20,5 +25,5 @@ sleep 10
 
 send_notification normal "System update completed" "You successfully updated to ${PRETTY_NAME}."
 
-
+# We don't really care if the notification went out or not
 exit 0
